---
title: "BDA 503 - Homework1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### About Me

My name is Busra Koc. I am a new graduate mechanical engineer. I am currently doing a master's degree in mechanical engineering at ITU. In my field, data analytics is very important as the other fields. But my main aim is specializing at data analytics to optimize life.

### Disciplined Convex Optimization with CVXR

This is video is about disciplined convex optimization with CVXR. CVXR is an R package that provides an object-oriented modeling language for convex optimization, similar to CVX, CVXPY, YALMIP, and Convex.jl. 
The speaker is talking about some linear equality constraints and functions. Interested in problems of this form for two reasons, first we can solve convex optimization problems and secondly convex optimization problems arise in many different applications including machine learning and statistics. There are some statistics problems in convex such as least squares, isotonic regression, logistic regression, sparse inverse covariance etc. She mentioned that in the past ten years DSLS or domain specific languages for convex optimization have risen in popularity. Lots of people using CVX, CVXPY, YALMIP and convex.jl in Matlab. Also the speaker mentions that capabilities of CVXR and some areas that using CVXR. And finally, she tells something about future work for CVXR like developing more applications, adding warm start support and further speed improvements. You can see the link of video below.

[Disciplined Convex Optimization with CVXR](https://www.youtube.com/watch?v=MyglbtnmQ8A)


## Examples

### How useful will R-Programming be for Mechanical Engineers?

R-Programming has adventages for mechanical engineers. For example, if you responsible from quality control, knowing statistics will make a huge difference, and knowing R is a huge plus in statistics.
And beware that you may need to use statistics for a lot of reasons besides quality control. It is how you measure productivity, track performance indicators, understand product trials, etc. Even maintenance is now very reliant on statistics, due to the preventive and predictive approaches developing right now.
In example case, the engineer recently used R to process data from field trials where he was getting around 30 different measurements from each trial, having a total of about 200 trials ( ~6000 measurements). This is part of a product development cycle, and the number of trials was optimized in advance using DOE methodology.

[How useful will R-Programming be for Mechanical Engineers?](https://www.quora.com/How-useful-will-R-Programming-be-for-Mechanical-Engineers)

### Control System Toolbox - System Interconnection

Dynamic systems are usually represented by a model before they can be analyzed computationally. These dynamic systems are systems that change, evolve or have their states altered or varied with time based on a set of defined rules. Dynamic systems could be mechanical, electrical, electronic, biological, sociological, and so on. Many such systems are usually defined by a set rules that are represented as a set of nonlinear differential equations. There are lots of functions about control system in Control System Toolbox like tranfer function "TF()", append function "append(sys1, sys2, ???, sysN)", series function "series(sys1, sys2)" parallel function "parallel(sys1, sys2)", feedback function "feedback(sys1, sys2)" etc. These are make easy and fast the calculations. 

[Control System Toolbox - System Interconnection](https://rviews.rstudio.com/2017/08/24/control-systems-toolbox/)

## R for Big Data in One Picture

This picture originally posted [here](https://www.xmind.net/m/LKF2/) covers the following topics:

- Basic stack
- Integrated platforms
- Visualization
- Data formats
- Large & out-of-memory data
- Hadoop
- Glue
- As backend
- GPU
- in-database analytics
- Parallel
- Efficiency
- Packages

[The Picture](rx.png)

[R for Big Data in One Picture](https://www.datasciencecentral.com/profiles/blogs/r-for-big-data-in-one-picture)

### Applications Of R Programming In R-eal World

During the most recent decade, the force originating from both the scholarly community and industry has lifted the R programming language to end up the absolute most significant tool for computational statistics, perception, and data science.

R Programming gives a broad variety of statistical (direct and nonlinear modeling), traditional statistical tests, time-arrangement analysis, grouping, bunching and graphical techniques, and is profoundly extensible. The S language is regularly the vehicle of decision for exploration in statistical methodology, and  R gives an Open Source route to cooperation in that action.

R Programming applications compass the universe from hypothetical, computational statistics and the hard sciences, for example, astronomy, chemistry, and genomics to practical applications in business, drug advancement, finance, health care, marketing, medicine and much more. Since R has almost 5,000 packages (libraries of functions) large portions of which are committed to particular applications, you don't need to be an R Programming genius to begin developing your applications.

Many quantitative analysts in finance use R Programming as their primary programming tool. Once you get the hang of it, it's good for everything from data import and cleaning, investigation and visualization, doing statistics and analyzes, all the route up to dealing simulations and generation trading applications, depending on what manner of strategy you're operating on.

You can find more information below.

[Applications Of R Programming In R-eal World](https://elearningindustry.com/applications-r-programming-r-eal-world)


